import { createContext, useContext, useMemo } from "react";

// --- Theme definitions ---
// Each theme maps semantic names to actual values.
// Components never see raw hex codes — only these names.

const devTheme = {
  name: "dev",
  colors: {
    bg: "#1a1714",
    surface: "#1e1b17",
    input: "#15130f",
    borderSubtle: "#2a2520",
    border: "#3a322a",
    hover: "#232019",
    overlay: "rgba(10, 9, 7, 0.85)",
    text: "#d4c9b8",
    textSecondary: "#b8ad9c",
    textTertiary: "#9a8e7d",
    textMuted: "#7a6f60",
    ghostText: "#6a5f52",
    textDim: "#5a5040",
    textFaint: "#4a4035",
    accent: "#c9a96e",
  },
  fonts: {
    body: "'EB Garamond', Georgia, serif",
    heading: "'Playfair Display', Georgia, serif",
    mono: "'JetBrains Mono', monospace",
  },
};

const playerTheme = {
  name: "player",
  colors: {
    bg: "#f0e8dc",
    surface: "#e8dfd0",
    input: "#faf6ef",
    borderSubtle: "#d4c8b4",
    border: "#c0b49c",
    hover: "#e4d9c8",
    overlay: "rgba(60, 50, 35, 0.75)",
    text: "#2c2418",
    textSecondary: "#4a3f30",
    textTertiary: "#6a5f4e",
    textMuted: "#8a7d6a",
    ghostText: "#a09480",
    textDim: "#8a7d6a",
    textFaint: "#b0a490",
    accent: "#8a6830",
  },
  fonts: {
    body: "'Caveat', cursive",
    heading: "'Caveat', cursive",
    mono: "'JetBrains Mono', monospace",
  },
};

export const themes = { dev: devTheme, player: playerTheme };

// --- Styles factory ---
// Takes a theme, returns the full styles object.
// Layout (padding, flex, widths) stays constant.
// Colors and fonts come from the theme.

export function createStyles(t) {
  const c = t.colors;
  const f = t.fonts;

  return {
    container: {
      fontFamily: f.body,
      maxWidth: 960,
      margin: "0 auto",
      display: "flex",
      gap: 0,
      height: "100vh",
      overflow: "hidden",
      background: c.bg,
      color: c.text,
      position: "relative",
    },
    sidebar: {
      width: 320,
      minWidth: 320,
      borderRight: `1px solid ${c.border}`,
      display: "flex",
      flexDirection: "column",
      background: c.surface,
      height: "100%",
    },
    sidebarHeader: {
      padding: "20px 16px 12px",
      borderBottom: `1px solid ${c.border}`,
      flexShrink: 0,
    },
    sidebarTitle: {
      fontFamily: f.heading,
      fontSize: 22,
      fontWeight: 900,
      letterSpacing: "0.04em",
      color: c.accent,
      margin: 0,
      textTransform: "uppercase",
    },
    sidebarSubtitle: {
      fontSize: 11,
      fontFamily: f.mono,
      color: c.textMuted,
      letterSpacing: "0.12em",
      textTransform: "uppercase",
      marginTop: 4,
    },
    filterRow: {
      display: "flex",
      gap: 4,
      padding: "10px 16px",
      borderBottom: `1px solid ${c.borderSubtle}`,
      flexShrink: 0,
    },
    filterBtn: (active) => ({
      background: active ? c.border : "transparent",
      border: "1px solid",
      borderColor: active ? c.accent : c.border,
      color: active ? c.accent : c.textMuted,
      padding: "3px 10px",
      borderRadius: 3,
      fontSize: 11,
      fontFamily: f.mono,
      cursor: "pointer",
      letterSpacing: "0.05em",
      transition: "all 0.15s ease",
    }),
    entryList: {
      flex: 1,
      overflowY: "auto",
      padding: "4px 0",
    },
    entryItem: (selected) => ({
      padding: "8px 12px",
      cursor: "pointer",
      background: selected ? c.borderSubtle : "transparent",
      borderLeft: `2px solid ${selected ? c.accent : "transparent"}`,
      transition: "all 0.12s ease",
      display: "flex",
      alignItems: "center",
      gap: 8,
    }),
    entryPortrait: {
      fontSize: 22,
      width: 36,
      height: 36,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      background: c.borderSubtle,
      borderRadius: "50%",
      flexShrink: 0,
    },
    entryName: {
      fontSize: 14,
      fontWeight: 600,
      color: c.text,
      lineHeight: 1.1,
    },
    entrySubtitle: {
      fontSize: 11,
      color: c.textMuted,
      fontFamily: f.mono,
      marginTop: 0,
    },
    addBtn: {
      margin: "8px 16px 12px",
      padding: "8px 0",
      background: "transparent",
      border: `1px dashed ${c.border}`,
      color: c.textMuted,
      borderRadius: 4,
      cursor: "pointer",
      fontFamily: f.body,
      fontSize: 14,
      transition: "all 0.15s ease",
      flexShrink: 0,
    },
    main: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
      height: "100%",
    },
    mainHeader: {
      padding: "20px 28px 16px",
      borderBottom: `1px solid ${c.borderSubtle}`,
      flexShrink: 0,
      display: "flex",
      alignItems: "flex-start",
      gap: 16,
    },
    mainPortrait: {
      fontSize: 36,
      width: 56,
      height: 56,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      background: c.borderSubtle,
      borderRadius: "50%",
      border: `2px solid ${c.border}`,
      flexShrink: 0,
    },
    mainName: {
      fontFamily: f.heading,
      fontSize: 28,
      fontWeight: 700,
      color: c.text,
      margin: 0,
      lineHeight: 1.1,
    },
    mainSubtitle: {
      fontSize: 13,
      color: c.accent,
      fontFamily: f.mono,
      marginTop: 4,
      letterSpacing: "0.03em",
    },
    tagsRow: {
      display: "flex",
      flexWrap: "wrap",
      gap: 6,
      marginTop: 8,
    },
    tag: {
      background: c.borderSubtle,
      border: `1px solid ${c.border}`,
      borderRadius: 3,
      padding: "2px 8px",
      fontSize: 11,
      fontFamily: f.mono,
      color: c.textTertiary,
    },
    tagKey: {
      color: c.textMuted,
    },
    tagValue: {
      color: c.accent,
    },
    notesSection: {
      flex: 1,
      padding: "0 28px 20px",
      overflowY: "auto",
      display: "flex",
      flexDirection: "column",
    },
    sectionLabel: {
      fontSize: 10,
      fontFamily: f.mono,
      color: c.textDim,
      letterSpacing: "0.15em",
      textTransform: "uppercase",
      marginTop: 20,
      marginBottom: 8,
    },
    notesArea: {
      width: "100%",
      minHeight: 120,
      background: c.input,
      border: `1px solid ${c.borderSubtle}`,
      borderRadius: 4,
      padding: "12px 14px",
      color: c.text,
      fontFamily: f.body,
      fontSize: 15,
      lineHeight: 1.6,
      resize: "vertical",
      outline: "none",
      transition: "border-color 0.15s ease",
      boxSizing: "border-box",
    },
    promptBox: {
      marginTop: 12,
      position: "relative",
    },
    promptInput: () => ({
      width: "100%",
      background: c.input,
      border: `1px solid ${c.borderSubtle}`,
      borderRadius: 4,
      padding: "10px 40px 10px 14px",
      color: c.text,
      fontFamily: f.body,
      fontSize: 15,
      lineHeight: 1.5,
      outline: "none",
      boxSizing: "border-box",
      transition: "border-color 0.15s ease",
    }),
    promptGhost: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 40,
      padding: "10px 14px",
      color: c.ghostText,
      fontFamily: f.body,
      fontSize: 15,
      lineHeight: 1.5,
      pointerEvents: "none",
      fontStyle: "italic",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    cycleBtn: {
      position: "absolute",
      right: 8,
      top: "50%",
      transform: "translateY(-50%)",
      background: "none",
      border: "none",
      color: c.textDim,
      cursor: "pointer",
      fontSize: 16,
      padding: "4px 6px",
      borderRadius: 3,
      transition: "color 0.15s ease",
      fontFamily: f.mono,
    },
    quickNote: {
      display: "flex",
      gap: 8,
      marginTop: 12,
      alignItems: "center",
    },
    quickNoteBtn: {
      background: c.borderSubtle,
      border: `1px solid ${c.border}`,
      borderRadius: 3,
      padding: "4px 10px",
      color: c.textTertiary,
      fontSize: 12,
      fontFamily: f.mono,
      cursor: "pointer",
      transition: "all 0.15s ease",
      whiteSpace: "nowrap",
    },
    savedEntries: {
      marginTop: 16,
      display: "flex",
      flexDirection: "column",
      gap: 8,
    },
    savedEntry: {
      background: c.surface,
      border: `1px solid ${c.borderSubtle}`,
      borderRadius: 4,
      padding: "10px 14px",
      fontSize: 14,
      lineHeight: 1.5,
      position: "relative",
    },
    savedTimestamp: {
      fontSize: 10,
      fontFamily: f.mono,
      color: c.textDim,
      marginBottom: 4,
    },
    savedText: {
      color: c.textSecondary,
    },
    deleteEntry: {
      position: "absolute",
      top: 8,
      right: 10,
      background: "none",
      border: "none",
      color: c.textFaint,
      cursor: "pointer",
      fontSize: 13,
      padding: "2px 4px",
      fontFamily: f.mono,
    },
    emptyState: {
      flex: 1,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
      color: c.textFaint,
      fontStyle: "italic",
      fontSize: 16,
      gap: 8,
    },
    modal: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: c.overlay,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 100,
    },
    modalCard: {
      background: c.surface,
      border: `1px solid ${c.border}`,
      borderRadius: 6,
      padding: "24px 28px",
      width: 380,
      maxWidth: "90%",
    },
    modalTitle: {
      fontFamily: f.heading,
      fontSize: 20,
      fontWeight: 700,
      color: c.accent,
      marginBottom: 16,
    },
    modalLabel: {
      fontSize: 10,
      fontFamily: f.mono,
      color: c.textDim,
      letterSpacing: "0.15em",
      textTransform: "uppercase",
      marginBottom: 4,
      marginTop: 12,
      display: "block",
    },
    modalInput: {
      width: "100%",
      background: c.input,
      border: `1px solid ${c.borderSubtle}`,
      borderRadius: 4,
      padding: "8px 12px",
      color: c.text,
      fontFamily: f.body,
      fontSize: 15,
      outline: "none",
      boxSizing: "border-box",
    },
    modalSelect: {
      width: "100%",
      background: c.input,
      border: `1px solid ${c.borderSubtle}`,
      borderRadius: 4,
      padding: "8px 12px",
      color: c.text,
      fontFamily: f.body,
      fontSize: 15,
      outline: "none",
      boxSizing: "border-box",
      appearance: "none",
    },
    modalActions: {
      display: "flex",
      gap: 8,
      marginTop: 20,
      justifyContent: "flex-end",
    },
    modalBtn: (primary) => ({
      background: primary ? c.accent : "transparent",
      border: primary ? "none" : `1px solid ${c.border}`,
      color: primary ? c.bg : c.textMuted,
      padding: "7px 18px",
      borderRadius: 4,
      cursor: "pointer",
      fontFamily: f.body,
      fontSize: 14,
      fontWeight: primary ? 600 : 400,
    }),
    exportBtn: {
      background: "none",
      border: "none",
      color: c.textDim,
      cursor: "pointer",
      fontSize: 11,
      fontFamily: f.mono,
      padding: "4px 8px",
      borderRadius: 3,
    },
    settingsBanner: {
      background: c.borderSubtle,
      borderBottom: `1px solid ${c.border}`,
      padding: "8px 28px",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      flexShrink: 0,
    },
    settingsLabel: {
      fontSize: 12,
      fontFamily: f.mono,
      color: c.textMuted,
    },
    toggle: (on) => ({
      width: 36,
      height: 20,
      borderRadius: 10,
      background: on ? c.accent : c.border,
      border: "none",
      cursor: "pointer",
      position: "relative",
      transition: "background 0.2s ease",
      flexShrink: 0,
    }),
    toggleDot: (on) => ({
      position: "absolute",
      top: 3,
      left: on ? 19 : 3,
      width: 14,
      height: 14,
      borderRadius: "50%",
      background: on ? c.bg : c.textDim,
      transition: "left 0.2s ease, background 0.2s ease",
    }),
  };
}

// --- Context ---

const ThemeContext = createContext();

export function ThemeProvider({ mode = "dev", children }) {
  const themeName = mode;
  const theme = themes[themeName] || themes.dev;
  const styles = useMemo(() => createStyles(theme), [theme]);

  const value = useMemo(
    () => ({ theme, styles, mode, themeName }),
    [theme, styles, mode, themeName],
  );

  return (
    <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>
  );
}

export function useTheme() {
  return useContext(ThemeContext);
}
